
version: '3'

services:
  chat-server:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - ./logs:/usr/src/app/logs